package main

import (
	"encoding/json"
	"flag"
	"fmt"
	"go/format"
	"os"
	"path/filepath"
	"sort"
	"strings"
	"unicode"

	"github.com/zeromicro/go-zero/tools/goctl/api/gogen"
	"github.com/zeromicro/go-zero/tools/goctl/api/spec"
	"github.com/zeromicro/go-zero/tools/goctl/plugin"
)

type endpointManifest struct {
	Endpoints []manifestEndpoint `json:"endpoints"`
}

type manifestEndpoint struct {
	Method string `json:"method"`
	Path   string `json:"path"`
}

type routeDefinition struct {
	Method       string
	Path         string
	ContractPath string
	MethodName   string
	EndpointName string
	RequestType  spec.Type
	ResponseType spec.Type
}

func main() {
	packageName := flag.String("package", "", "generated Go package name")
	outputDir := flag.String("output", "", "generated output directory")
	manifestPath := flag.String("manifest", "", "allowed endpoint manifest")
	flag.Parse()

	if *packageName == "" || *outputDir == "" || *manifestPath == "" {
		fmt.Fprintln(os.Stderr, "--package, --output, and --manifest are required")
		os.Exit(2)
	}
	if err := generate(*packageName, *outputDir, *manifestPath); err != nil {
		fmt.Fprintln(os.Stderr, err)
		os.Exit(1)
	}
}

func generate(packageName, outputDir, manifestPath string) error {
	pl, err := plugin.NewPlugin()
	if err != nil {
		return fmt.Errorf("read goctl plugin input: %w", err)
	}
	if pl.Api == nil {
		return fmt.Errorf("goctl plugin did not provide an API specification")
	}
	allowed, err := loadManifest(manifestPath)
	if err != nil {
		return err
	}
	routes, err := collectRoutes(pl.Api, allowed)
	if err != nil {
		return err
	}
	selectedTypes, err := selectTypes(pl.Api.Types, routes)
	if err != nil {
		return err
	}
	types, err := gogen.BuildTypes(selectedTypes)
	if err != nil {
		return fmt.Errorf("build API types: %w", err)
	}
	if err := os.MkdirAll(outputDir, 0o755); err != nil {
		return fmt.Errorf("create output directory: %w", err)
	}
	if err := writeGo(filepath.Join(outputDir, "types_gen.go"), fmt.Sprintf("// Code generated by ctfpc9n-api-gen. DO NOT EDIT.\n\npackage %s\n\n%s\n", packageName, types)); err != nil {
		return err
	}
	return writeGo(filepath.Join(outputDir, "endpoints_gen.go"), endpointsSource(packageName, routes))
}

func loadManifest(filename string) (map[string]struct{}, error) {
	data, err := os.ReadFile(filename)
	if err != nil {
		return nil, fmt.Errorf("read endpoint manifest: %w", err)
	}
	var manifest endpointManifest
	if err := json.Unmarshal(data, &manifest); err != nil {
		return nil, fmt.Errorf("decode endpoint manifest: %w", err)
	}
	if len(manifest.Endpoints) == 0 {
		return nil, fmt.Errorf("endpoint manifest is empty")
	}
	allowed := make(map[string]struct{}, len(manifest.Endpoints))
	for _, endpoint := range manifest.Endpoints {
		method := strings.ToUpper(strings.TrimSpace(endpoint.Method))
		path := strings.TrimSpace(endpoint.Path)
		if method == "" || !strings.HasPrefix(path, "/agent/v1/") {
			return nil, fmt.Errorf("invalid endpoint manifest entry %q %q", endpoint.Method, endpoint.Path)
		}
		key := method + " " + path
		if _, exists := allowed[key]; exists {
			return nil, fmt.Errorf("duplicate endpoint manifest entry %s", key)
		}
		allowed[key] = struct{}{}
	}
	return allowed, nil
}

func collectRoutes(api *spec.ApiSpec, allowed map[string]struct{}) ([]routeDefinition, error) {
	service := api.Service.JoinPrefix()
	routes := make([]routeDefinition, 0, len(allowed))
	seen := make(map[string]struct{}, len(allowed))
	for _, route := range service.Routes() {
		method := strings.ToUpper(route.Method)
		path := route.Path
		key := method + " " + path
		if _, ok := allowed[key]; !ok {
			continue
		}
		if _, exists := seen[key]; exists {
			return nil, fmt.Errorf("duplicate API route %s", key)
		}
		seen[key] = struct{}{}
		name := exportedIdentifier(route.Handler)
		if name == "" {
			name = exportedIdentifier(method + " " + path)
		}
		relativePath := strings.TrimPrefix(path, "/agent/v1")
		if relativePath == path || relativePath == "" {
			return nil, fmt.Errorf("endpoint %s is not under /agent/v1", key)
		}
		routes = append(routes, routeDefinition{
			Method: method, Path: relativePath, ContractPath: path, MethodName: name, EndpointName: "Endpoint" + name,
			RequestType: route.RequestType, ResponseType: route.ResponseType,
		})
	}
	if len(seen) != len(allowed) {
		missing := make([]string, 0, len(allowed)-len(seen))
		for key := range allowed {
			if _, ok := seen[key]; !ok {
				missing = append(missing, key)
			}
		}
		sort.Strings(missing)
		return nil, fmt.Errorf("endpoint manifest routes missing from contract: %s", strings.Join(missing, ", "))
	}
	sort.Slice(routes, func(i, j int) bool { return routes[i].MethodName < routes[j].MethodName })
	return routes, nil
}

func selectTypes(types []spec.Type, routes []routeDefinition) ([]spec.Type, error) {
	definitions := make(map[string]spec.DefineStruct, len(types))
	for _, typ := range types {
		definition, ok := typ.(spec.DefineStruct)
		if !ok {
			return nil, fmt.Errorf("unsupported API definition type %T", typ)
		}
		if _, exists := definitions[definition.Name()]; exists {
			return nil, fmt.Errorf("duplicate API type %s", definition.Name())
		}
		definitions[definition.Name()] = definition
	}

	selected := make(map[string]struct{}, len(routes)*2)
	var visit func(spec.Type) error
	visit = func(typ spec.Type) error {
		if typ == nil {
			return nil
		}
		switch definition := typ.(type) {
		case spec.DefineStruct:
			name := definition.Name()
			if _, exists := selected[name]; exists {
				return nil
			}
			definition, exists := definitions[name]
			if !exists {
				return fmt.Errorf("referenced API type %s is missing", name)
			}
			selected[name] = struct{}{}
			for _, member := range definition.Members {
				if err := visit(member.Type); err != nil {
					return err
				}
			}
			return nil
		case spec.PointerType:
			return visit(definition.Type)
		case spec.ArrayType:
			return visit(definition.Value)
		case spec.MapType:
			return visit(definition.Value)
		case spec.PrimitiveType, spec.InterfaceType:
			return nil
		default:
			return fmt.Errorf("unsupported referenced API type %T", typ)
		}
	}

	for _, route := range routes {
		if err := visit(route.RequestType); err != nil {
			return nil, err
		}
		if err := visit(route.ResponseType); err != nil {
			return nil, err
		}
	}

	result := make([]spec.Type, 0, len(selected))
	for _, typ := range types {
		if _, exists := selected[typ.Name()]; exists {
			result = append(result, typ)
		}
	}
	return result, nil
}

func exportedIdentifier(value string) string {
	var builder strings.Builder
	uppercase := true
	for _, char := range value {
		if !unicode.IsLetter(char) && !unicode.IsDigit(char) {
			uppercase = true
			continue
		}
		if builder.Len() == 0 && unicode.IsDigit(char) {
			builder.WriteString("Route")
		}
		if uppercase {
			builder.WriteRune(unicode.ToUpper(char))
			uppercase = false
		} else {
			builder.WriteRune(char)
		}
	}
	return builder.String()
}

func endpointsSource(packageName string, routes []routeDefinition) string {
	var source strings.Builder
	fmt.Fprintf(&source, "// Code generated by ctfpc9n-api-gen. DO NOT EDIT.\n\npackage %s\n\n", packageName)
	source.WriteString("type Endpoint struct {\n\tName string\n\tMethod string\n\tPath string\n\tContractPath string\n}\n\nvar (\n")
	for _, route := range routes {
		fmt.Fprintf(&source, "\t%s = Endpoint{Name: %q, Method: %q, Path: %q, ContractPath: %q}\n", route.EndpointName, route.MethodName, route.Method, route.Path, route.ContractPath)
	}
	source.WriteString(")\n")
	return source.String()
}

func writeGo(filename, source string) error {
	formatted, err := format.Source([]byte(source))
	if err != nil {
		return fmt.Errorf("format generated %s: %w", filename, err)
	}
	if err := os.WriteFile(filename, formatted, 0o644); err != nil {
		return fmt.Errorf("write generated %s: %w", filename, err)
	}
	return nil
}
